{{- if .Values.postgresql.enabled }}
{{- $pgSecretName := printf "%s-postgresql" (include "opengeo-data.fullname" .) }}
{{- $existingPgSecret := (lookup "v1" "Secret" .Release.Namespace $pgSecretName) }}
{{- $password := .Values.postgresql.password | default "" }}
{{- if and (not $password) $existingPgSecret }}
{{- $password = index $existingPgSecret.data "password" | b64dec }}
{{- end }}
{{- if not $password }}
{{- $password = randAlphaNum 24 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opengeo-data.databaseSecretName" . }}
  labels:
    {{- include "opengeo-data.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.postgresql.username | default "opengeo" }}:{{ $password }}@{{ $pgSecretName }}:5432/{{ .Values.postgresql.database | default "opengeo" }}"
  PG_PASSWORD: "{{ $password }}"
{{- end }}
